"""
Curated scholarship dataset.

No comprehensive free scholarship-listing API exists (confirmed: DAAD,
Scholarships.com, and StudyPortals have no public developer APIs). This is
a hand-maintained list of real, well-known, currently-active fully-funded
scholarship programs, used as the reliable baseline. ScholarshipAPI.com
(scholarship_api_client.py) supplements this with live data where it has
coverage (currently Australia/NZ universities only).

Update this list periodically - deadlines shift year to year, so treat the
`deadline` field as "typical annual window," not a guarantee, and always
point people to the official URL to confirm.
"""
from app.schemas import ScholarshipResult

CURATED_SCHOLARSHIPS: list[ScholarshipResult] = [
    ScholarshipResult(
        source="curated",
        external_id="daad-epos",
        name="DAAD EPOS Scholarship",
        provider="DAAD (Germany)",
        country="Germany",
        degree_levels=["masters", "phd"],
        fields_of_study=["development studies", "engineering", "economics", "public policy"],
        funding_type="fully_funded",
        deadline="Typically October each year",
        url="https://www.daad.de/en/study-and-research-in-germany/scholarships/",
        description="Funds postgraduate study in Germany for students from developing/emerging countries, covering tuition, monthly stipend, health insurance, and travel allowance.",
    ),
    ScholarshipResult(
        source="curated",
        external_id="chevening",
        name="Chevening Scholarship",
        provider="UK Government (FCDO)",
        country="United Kingdom",
        degree_levels=["masters"],
        fields_of_study=["all subjects"],
        funding_type="fully_funded",
        deadline="Typically November each year",
        url="https://www.chevening.org/",
        description="UK government's global scholarship programme, fully funding a one-year master's degree at any UK university, aimed at future leaders and influencers.",
    ),
    ScholarshipResult(
        source="curated",
        external_id="fulbright",
        name="Fulbright Foreign Student Program",
        provider="US Department of State",
        country="United States",
        degree_levels=["masters", "phd"],
        fields_of_study=["all subjects"],
        funding_type="fully_funded",
        deadline="Varies by country, typically Feb-May",
        url="https://foreign.fulbrightonline.org/",
        description="Fully funds graduate study, research, or teaching in the US, covering tuition, living stipend, airfare, and health insurance.",
    ),
    ScholarshipResult(
        source="curated",
        external_id="erasmus-mundus",
        name="Erasmus Mundus Joint Master Degrees",
        provider="European Union",
        country="Multiple (EU)",
        degree_levels=["masters"],
        fields_of_study=["all subjects"],
        funding_type="fully_funded",
        deadline="Typically December-January (varies by programme)",
        url="https://www.eacea.ec.europa.eu/scholarships_en",
        description="Fully funded master's degrees studied across at least two European countries, covering tuition, travel, installation costs, and monthly stipend.",
    ),
    ScholarshipResult(
        source="curated",
        external_id="commonwealth",
        name="Commonwealth Scholarship",
        provider="UK Government",
        country="United Kingdom",
        degree_levels=["masters", "phd"],
        fields_of_study=["all subjects", "priority: development-related"],
        funding_type="fully_funded",
        deadline="Typically December-January",
        url="https://cscuk.fcdo.gov.uk/",
        description="For citizens of Commonwealth countries to study master's or PhD programmes in the UK, covering tuition, living allowance, and travel.",
    ),
    ScholarshipResult(
        source="curated",
        external_id="australia-awards",
        name="Australia Awards Scholarships",
        provider="Australian Government",
        country="Australia",
        degree_levels=["masters", "phd"],
        fields_of_study=["all subjects"],
        funding_type="fully_funded",
        deadline="Typically April-June (varies by country)",
        url="https://www.australiaawardsindopacific.org/",
        description="Long-term development scholarships for full-time study in Australia, covering tuition, living expenses, travel, and health cover.",
    ),
    ScholarshipResult(
        source="curated",
        external_id="gates-cambridge",
        name="Gates Cambridge Scholarship",
        provider="University of Cambridge",
        country="United Kingdom",
        degree_levels=["masters", "phd"],
        fields_of_study=["all subjects"],
        funding_type="fully_funded",
        deadline="Typically October-December (varies by course)",
        url="https://www.gatescambridge.org/",
        description="Fully funds postgraduate study at the University of Cambridge for outstanding applicants from outside the UK, covering all fees plus a maintenance allowance.",
    ),
    ScholarshipResult(
        source="curated",
        external_id="aga-khan",
        name="Aga Khan Foundation International Scholarship Programme",
        provider="Aga Khan Foundation",
        country="Multiple",
        degree_levels=["masters", "phd"],
        fields_of_study=["all subjects"],
        funding_type="partially_funded",
        deadline="Typically March each year",
        url="https://www.akdn.org/our-agencies/aga-khan-foundation/international-scholarship-programme",
        description="Provides scholarships as a combination of grants and loans for graduate study, prioritizing students without other means of financing further education.",
    ),
    ScholarshipResult(
        source="curated",
        external_id="schwarzman",
        name="Schwarzman Scholars",
        provider="Tsinghua University, China",
        country="China",
        degree_levels=["masters"],
        fields_of_study=["public policy", "international relations", "business"],
        funding_type="fully_funded",
        deadline="Typically September each year",
        url="https://www.schwarzmanscholars.org/",
        description="One-year master's in Global Affairs at Tsinghua University, Beijing, fully funded including tuition, travel, technology, and stipend.",
    ),
    ScholarshipResult(
        source="curated",
        external_id="daad-in-country",
        name="DAAD In-Country/In-Region Scholarship Programmes",
        provider="DAAD (Germany)",
        country="Multiple (partner universities)",
        degree_levels=["masters"],
        fields_of_study=["development-related subjects"],
        funding_type="fully_funded",
        deadline="Varies by country/partner university",
        url="https://www.daad.de/en/study-and-research-in-germany/scholarships/",
        description="DAAD-funded master's programmes at partner universities within the applicant's home region, reducing relocation costs while still fully funded.",
    ),
    ScholarshipResult(
        source="curated",
        external_id="turkiye-burslari",
        name="Türkiye Bursları (Turkey Scholarships)",
        provider="Turkish Government",
        country="Turkey",
        degree_levels=["bachelors", "masters", "phd"],
        fields_of_study=["all subjects"],
        funding_type="fully_funded",
        deadline="Typically January-February each year",
        url="https://www.turkiyeburslari.gov.tr/",
        description="Fully funds bachelor's, master's, and PhD study in Turkey for international students, covering tuition, monthly stipend, accommodation, health insurance, and a one-year Turkish language course.",
    ),
    ScholarshipResult(
        source="curated",
        external_id="brunei-darussalam",
        name="Brunei Darussalam Government Scholarship",
        provider="Government of Brunei",
        country="Brunei",
        degree_levels=["bachelors", "masters"],
        fields_of_study=["all subjects"],
        funding_type="fully_funded",
        deadline="Typically February-March each year",
        url="https://www.mofa.gov.bn/Pages/Scholarship.aspx",
        description="Fully funds undergraduate and postgraduate study in Brunei for students from ASEAN, Commonwealth, and OIC member countries, covering tuition, living allowance, and travel.",
    ),
    ScholarshipResult(
        source="curated",
        external_id="orange-knowledge",
        name="Orange Knowledge Programme",
        provider="Dutch Government (Nuffic)",
        country="Netherlands",
        degree_levels=["bachelors", "masters"],
        fields_of_study=["all subjects"],
        funding_type="fully_funded",
        deadline="Varies by course, typically opens annually",
        url="https://www.nuffic.nl/en/subjects/orange-knowledge-programme",
        description="Funds short courses, bachelor's, and master's study in the Netherlands for professionals from a defined list of developing countries, covering tuition and living costs.",
    ),
    ScholarshipResult(
        source="curated",
        external_id="undergraduate-hu-jinnah",
        name="HEC Need-Based Undergraduate Scholarship Program",
        provider="Higher Education Commission, Pakistan",
        country="Pakistan",
        degree_levels=["bachelors"],
        fields_of_study=["all subjects"],
        funding_type="fully_funded",
        deadline="Announced annually via HEC website",
        url="https://hec.gov.pk/english/scholarshipsgrants/",
        description="Need-based fully-funded undergraduate scholarships for Pakistani students at HEC-recognized universities, covering tuition and a living stipend.",
    ),
]